
project_id = "dtrlmfwgtjrjkepvgatv"
import_map = "./import_map.json"

[functions.verify-wallet-signature]

[functions.process-crypto-transaction]

[functions.sync-blockchain-data]

[functions.create-token-metadata]
