import { User, Tweet } from './types';

export const mockUsers: User[] = [
  {
    id: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    bio: 'Crypto enthusiast and developer',
    joinedDate: '2024-01-01',
    following: [],
    followers: [],
    verified: true
  },
  {
    id: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    bio: 'NFT collector and artist',
    joinedDate: '2024-02-15',
    following: [],
    followers: [],
    verified: false
  },
  {
    id: '3',
    username: 'satoshi',
    displayName: 'Satoshi Nakamoto',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Satoshi',
    bio: 'Bitcoin creator',
    joinedDate: '2009-01-03',
    following: [],
    followers: [],
    verified: true
  },
];

export const mockTweets: Tweet[] = [
  {
    id: '101',
    content: 'Just bought some more BTC! #Bitcoin #Crypto',
    user: mockUsers[0],
    timestamp: '2024-03-20T10:00:00Z',
    likes: 150,
    retweets: 50,
    comments: 20,
    attachments: [],
    mentions: [],
    hashtags: ['Bitcoin', 'Crypto'],
  },
  {
    id: '102',
    content: 'Excited about the new NFT drop! #NFT #Art',
    user: mockUsers[1],
    timestamp: '2024-03-20T11:30:00Z',
    likes: 200,
    retweets: 75,
    comments: 30,
    attachments: [],
    mentions: [],
    hashtags: ['NFT', 'Art'],
  },
  {
    id: '103',
    content: 'Is DeFi the future of finance? 🤔 #DeFi',
    user: mockUsers[0],
    timestamp: '2024-03-20T13:00:00Z',
    likes: 120,
    retweets: 40,
    comments: 15,
    attachments: [],
    mentions: [],
    hashtags: ['DeFi'],
  },
  {
    id: '104',
    content: 'Check out my latest blog post on blockchain technology! 🚀',
    user: mockUsers[2],
    timestamp: '2024-03-20T14:45:00Z',
    likes: 180,
    retweets: 60,
    comments: 25,
    attachments: [],
    mentions: [],
    hashtags: ['Blockchain'],
  },
  {
    id: '105',
    content: 'What are your thoughts on the current market trends? #MarketAnalysis',
    user: mockUsers[1],
    timestamp: '2024-03-20T16:00:00Z',
    likes: 90,
    retweets: 30,
    comments: 10,
    attachments: [],
    mentions: [],
    hashtags: ['MarketAnalysis'],
  },
];
