
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { DbUser, DbTweet, DbComment } from '@/lib/db-types';

const SUPABASE_URL = "https://dtrlmfwgtjrjkepvgatv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0cmxtZndndGpyamtlcHZnYXR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNDM3NjUsImV4cCI6MjA1ODYxOTc2NX0.6nB2HwLdPQynPYowwoHVF17wG8G85sGXcu79AsOJe9g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Type-safe table accessors
export const usersTable = () => supabase.from('users');
export const tweetsTable = () => supabase.from('tweets');
export const commentsTable = () => supabase.from('comments');

export type SupabaseClient = typeof supabase;
